# THEME DARK BLUEJ LIGHT SATURATION

# vk codes
CODE_PLAYPAUSE=0xB3
CODE_NEXT=0xB0
CODE_PREV=0xB1

# text sizes
FONT="Century Gothic Bold"
SONG_TEXT_SIZE=25
ARTIST_TEXT_SIZE=12
INPUT_FONT_SIZE=26

# colors
TRANSPARENT="transparent"

DARK_DEFAULT="#1E1E1E"
# DARK_DEFAULT_SECONDARY="#3f4653"
DARK_DEFAULT_SECONDARY="#3f534a"

WHITE="#F2F2F2"
BLACK="#1F1F1F"
BLACK_2="#2b2b2b"

RED="#400000"
ORANGE="#402100"
YELLOW="#3e4000"
GREEN_LIGHT="#004003"
GREEN="#011f03"
BLUE="#002840"
BLUE_DARK="#040040"
PURPLE="#2f0040"
PINK="#40002c"

FG_COLOR=DARK_DEFAULT
FG_COLOR_SECONDARY=DARK_DEFAULT_SECONDARY
TEXT_COLOR="#ccd0d8"
TEXT_COLOR_SECONDARY="#7b8c9f"
TITLE_HEX_COLOR=0x001E1E1E

# icons
ICO_EMPTY_LIGHT="icons/empty.ico"
ICO_PAUSE_LIGHT="icons/pause.ico"
ICO_PLAY_LIGHT="icons/play.ico"
ICO_NEXT_LIGHT="icons/next.ico"
ICO_PREV_LIGHT="icons/prev.ico"

ICO_EMPTY_DARK="icons/empty_w.png"
ICO_PAUSE_DARK="icons/pause_w.png"
ICO_PLAY_DARK="icons/play_w.png"
ICO_NEXT_DARK="icons/next_w.png"
ICO_PREV_DARK="icons/prev_w.png"